BEGIN;

DROP TABLE IF EXISTS "book_genre", "genre", "book";

-- table books

CREATE TABLE "book" (
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "title" VARCHAR(255) NOT NULL UNIQUE,
  "author" VARCHAR(255) NOT NULL,
  "description" TEXT
);

-- table genre 

CREATE TABLE "genre" (
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(100) NOT NULL UNIQUE
);

-- Table de liaison 

CREATE TABLE "book_genre" (
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "book_id" INT NOT NULL REFERENCES "book"("id") ON DELETE CASCADE,
  "genre_id" INT NOT NULL REFERENCES "genre"("id") ON DELETE CASCADE
);

COMMIT;
